#line 2 "au_autodiff_generate_template.cpp"
#include <math.h>

#define MLX_NO_MEXFUNCTION
#include "au_mex.h"

// Autogenerated by au_ccode
// FROM: @VarName
// au_autodiff_template.cpp - outline code for au_autodiff*
// awf@microsoft.com, Dec 13

extern "C"
void mexFunction( int nlhs, mxArray *plhs[],
                  int nrhs, const mxArray *prhs[])
{
    if(nrhs!= 2)
        mexErrMsgTxt("2 inputs required (in, data).");
    if(nlhs!=1)
        mexErrMsgTxt("One output required.");

    mlx_inputs  ins(nrhs, prhs); // Wrap inputs
    mlx_outputs outs(nlhs, plhs); // Wrap outputs
    
    mlx_array<double> in(ins[0]);
    mlx_array<double> data(ins[1]);

    mlx_assert(in.cols == data.cols);

    mlx_make_array<double> out(@OutRows, in.cols);

    double const* in_ptr = in.data;
    double const* data_ptr = data.data;
    double* out_ptr = out.data;

    for(int c_in = 0; c_in < in.cols; 
            ++c_in,
            in_ptr += in.rows,
            data_ptr += data.rows, 
            out_ptr += out.rows) {
       @Body
    }
    
    outs[0] = out;
}
