$password = read-host "Enter codeplex password:"

# Generate MATLAB help file
./make-matlabhelp

# Generate the HTML
@"
<h1>au_mex classes reference</h1>
Autogenerated from doc/au_mex_reference.txt
<br/>
"@ | out-file -enc ascii au_mex_reference.html
cat au_mex_reference.txt | % {
  "$_<br/>"
} | out-file -append -enc ascii au_mex_reference.html

# Publish...
write-host "Finding blog post"
$p = ../powershell/metaweblog-get-posts.ps1 https://www.codeplex.com/site/metaweblog awful awfidius $password 10000
$post = $p | ? { $_.title -eq 'au_mex_reference' }
write-host "Found post $($post.postId)"

$post.description = cat au_mex_reference.html

write-host "Posting update"
$out = ..\powershell\metaweblog-methodcall.ps1 https://www.codeplex.com/site/metaweblog editPost ($post.postId) awfidius $password $post.ToString() "<boolean>1</boolean>"

