$password = read-host "Enter codeplex password:"

# Generate MATLAB help files
./make-matlabhelp

copy Documentation.html Home.html

# Generate au_mex_reference.html
@"
<h1>au_mex classes reference</h1>
Autogenerated from doc/au_mex_reference.txt
<br/>
"@ | out-file -enc ascii au_mex_reference.html
cat au_mex_reference.txt | % {
  "$_<br/>"
} | out-file -append -enc ascii au_mex_reference.html

# Create MatlabAllHelp.html
matlab -wait -norc -nosplash -nodisplay -noFigureWindows -nodesktop -r 'au_makedoc;exit'

# Publish...
write-host "Finding blog post"
$p = ../powershell/metaweblog-get-posts.ps1 https://www.codeplex.com/site/metaweblog awful awfidius $password 10000

foreach($page in @('Home', 'au_mex_reference', 'Documentation', 'MatlabAllHelp')) {
  # mex_ref
  $post = $p | ? { $_.title -eq $page }
  write-host "Found post $($post.postId) for page [$page]"

  $post.description = cat "$page.html"

  write-host "Posting update"
  $out = ..\powershell\metaweblog-methodcall.ps1 https://www.codeplex.com/site/metaweblog editPost ($post.postId) awfidius $password $post.ToString() "<boolean>1</boolean>"
}
