# Generate the MATLAB help file
cat au_mex_reference.txt | % -PROCESS {
  $_ = $_ -replace '<pre>',''
  $_ = $_ -replace '</pre>',''
  "% $_"
} -END { 
  ""
  "% Autogenerated by ../doc/make-matlabhelp.ps1"
} | out-file -enc ascii ../matlab/au_mex.m

# Generate the MATLAB Contents file
cat au_mex_reference.txt | % -PROCESS {
  $_ = $_ -replace '<pre>',''
  $_ = $_ -replace '</pre>',''
  "% $_"
} -END { 
  ""
  "% Autogenerated by ../doc/make-matlabhelp.ps1"
} | out-file -enc ascii ../matlab/au_mex.m
