$password = read-host "Enter codeplex password:"

# Create MatlabAllHelp.html
# there's a race here, and -wait should fix it but doesn't.  
# Waiting for mathworks to fix.
matlab -wait -norc -nosplash -nodisplay -noFigureWindows -nodesktop -r 'au_makedoc;exit'

# Generate the MATLAB help file for au_mex from au_mex_reference.txt
cat au_mex_reference.txt | % -PROCESS {
  $_ = $_ -replace '<pre>',''
  $_ = $_ -replace '</pre>',''
  "% $_"
} -END { 
  ""
  "% Autogenerated by ../doc/make-matlabhelp.ps1"
} | out-file -enc ascii ../matlab/au_mex.m

# Generate au_mex_reference.html
@"
<h1>au_mex classes reference</h1>
Autogenerated from doc/au_mex_reference.txt
<br/>
"@ | out-file -enc ascii au_mex_reference.html
cat au_mex_reference.txt | % {
  "$_<br/>"
} | out-file -append -enc ascii au_mex_reference.html

# Home page and doc page are the same.
copy Documentation.html Home.html

# Publish...
write-host "Finding blog post"
$p = ../powershell/metaweblog-get-posts.ps1 https://www.codeplex.com/site/metaweblog awful awfidius $password 10000

foreach($page in @('Home', 'au_mex_reference', 'Documentation', 'MatlabAllHelp')) {
  # mex_ref
  $post = $p | ? { $_.title -eq $page }
  write-host "Found post $($post.postId) for page [$page]"

  $post.description = cat "$page.html"

  write-host "Posting update"
  $out = ..\powershell\metaweblog-methodcall.ps1 https://www.codeplex.com/site/metaweblog editPost ($post.postId) awfidius $password $post.ToString() "<boolean>1</boolean>"
}
